FROM python:3.8-slim-buster
WORKDIR /app
RUN apt-get update 
RUN apt-get install -y python3-dev default-libmysqlclient-dev build-essential
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install mysqlclient==2.1.1
COPY . /app

CMD ["python", "magi_main.py"]